### ISSUE TITLE
MVPリリースレビュー

### ISSUE THREAD

**Issue by tmtkzk0823** [reiji820/planet#25]
@reiji820 
お疲れ様です！
こちらMVPリリースレビューになります！

### 技術
基本的なことはできているかつ、テストもしっかり書かれている点がいいと思いました。
まずは技術面はREADMEの**その後の機能**に記載してある機能を実装していきましょう。
細かい点になりますが、以下FBになります。
- `master.key`がgitの管理下に入ってしまっていてGitHubにpushされてしまっているので、早急に`master.key`を作成しなおし、awsやapiのkeyの再登録や変更をしてください。また、変更後はmaster.keyを.gitignoreファイルに記載してgitの管理下から外してください。
- `app/controllers/time_schedules_controller.rb`のcreateアクション内の`@schedules = TimeSchedule.where(post_id: params[:id]).page(params[:page]).per(10)`で@schedulesに代入しているかと思うのですが、この変数がどちらで使われているのかわからなかったので、ご確認をお願いします。（使用している場所を見逃していたら申し訳ありません。）

### ユーザビリティ
色合いやテキストの行体などで、しっかり世界観が出せている印象でした！直感的にも使いやすくなっていると思います。
上記を踏まえて、以下FBとなります。
- 現状、投稿一覧ページがTOPページになっているかと思いますが、可能であれば**アプリTOPページを別で用意し、そのページで使い方説明等がある**と、ユーザーがアプリに訪れた際、迷わず使い始めることができるかと思いました。（その際、アプリのタイトル、サブタイトル等があるとよりいいかと思います。）

以上です！
全体的に、デザインよく、特に迷わず使用できるアプリだと思いました！
LGTMです！
上記の内容を本リリース実装するタスクに組み込み、スケジュールを立ててみてください。
スケジュール決まりましたら共有をお願いできればと思います。

また上記レビューに関して、質問などありましたらスレッドに記載いただいてご連絡ください！

**Comment by reiji820** [comment]
レビューありがとうございます！かしこまりました！master.keyの方見落としていました！早急に対応します。
また、createアクションの方不要なのに何故か記載してしまっていました！助かりました！

**Comment by reiji820** [comment]
createアクションの方不要だと思っていましたが、時刻が未入力または予定が未入力の場合にエラーが起きていたので、そちらの対処のために記載していました！先ほどテストで判明しました
